//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CvDBEntities1 : DbContext
    {
        public CvDBEntities1()
            : base("name=CvDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN> ADMIN { get; set; }
        public virtual DbSet<ADRES> ADRES { get; set; }
        public virtual DbSet<CALISMALAR> CALISMALAR { get; set; }
        public virtual DbSet<HAKKIMDA> HAKKIMDA { get; set; }
        public virtual DbSet<ILETISIM> ILETISIM { get; set; }
        public virtual DbSet<LINKLER> LINKLER { get; set; }
        public virtual DbSet<YETENEKLER> YETENEKLER { get; set; }
    }
}
